import bcryptjs from 'bcryptjs';

export interface SeedProduct {
    id: number;
    description: string;
    inStock: number;
    price: number;
    slug: string;
    title: string;
    subcategoryId: number;
    images: string[];
    sizes?: string[];
    colors?: string[];
    numbers?: string[];
    genders?: string[];
    tags?: string[];
}

interface SeedCategory {
    id: number;
    name: string;
    icon: number;
}

interface SeedUser {
    email: string;
    password: string;
    name: string;
    roleId: number;
}

interface SeedData {
    genders: { id: number, name: string }[];
    colors: { id: number, name: string }[];
    sizes: { id: number, name: string }[];
    roles: { id: number, name: string }[];
    categories: SeedCategory[];
    users: SeedUser[];
    products: SeedProduct[];
}

export const initialData: SeedData = {
    genders: [
        { id: 1, name: 'Hombre ' },
        { id: 2, name: 'Mujer' },
        { id: 3, name: 'Niño' },
    ],
    colors: [
        { id: 1, name: '#ff0000' },
        { id: 2, name: '#00ff00' },
        { id: 3, name: '#0000ff' },
    ],
    sizes: [
        { id: 1, name: 'S' },
        { id: 2, name: 'M' },
        { id: 3, name: 'L' },
        { id: 4, name: 'XL' },
        { id: 5, name: 'XXL' },
    ],
    roles: [
        { id: 1, name: 'admin' },
        { id: 2, name: 'user' }
    ],
    categories: [
        { id: 1, name: "Accesorios", icon: 1 },
        { id: 2, name: "Globos", icon: 5 },
        { id: 3, name: "Disfraces", icon: 9 },
        { id: 4, name: "Mascaras", icon: 7 },
        { id: 5, name: "Para la mesa", icon: 11 },
        { id: 6, name: "Adultos", icon: 3 },
        { id: 7, name: "Infantil", icon: 2 },
        { id: 8, name: "Celebraciones", icon: 4 },
        { id: 9, name: "Despedidas", icon: 6 },
    ],
    users: [
        {
            email: 'admin@test.com',
            name: 'Alejandro Admin',
            password: bcryptjs.hashSync('123456'),
            roleId: 1
        },
        {
            email: 'paolo@test.com',
            name: 'Paolo Test',
            password: bcryptjs.hashSync('123456'),
            roleId: 2
        }
    ],
    products: [
        {
            id: 1,
            description: "Set de globos metálicos en colores vibrantes para decorar cualquier celebración.",
            inStock: 7,
            price: 75000,
            slug: "mens_chill_crew_neck_sweatshirt",
            title: "Set de globos metálicos",
            subcategoryId: 26,
            numbers: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
            images: [
                '1740176-00-A_0_2000.jpg',
                '1740176-00-A_1.jpg',
            ],
        },
        {
            id: 2,
            description: "Guirnaldas LED para iluminar fiestas con un ambiente mágico.",
            inStock: 5,
            price: 20000,
            slug: "men_quilted_shirt_jacket",
            title: "Guirnaldas LED para iluminar fiestas",
            subcategoryId: 12,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740507-00-A_0_2000.jpg',
                '1740507-00-A_1.jpg',
            ],
        },
        {
            id: 3,
            description: "Confeti en forma de estrellas doradas para una decoración elegante.",
            inStock: 10,
            price: 13000,
            slug: "men_raven_lightweight_zip_up_bomber_jacket",
            title: "Confeti en forma de estrellas doradas",
            subcategoryId: 7,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740250-00-A_0_2000.jpg',
                '1740250-00-A_1.jpg'
            ],
        },

        {
            id: 4,
            description: "Disfraz de pirata con accesorios incluidos para eventos temáticos.",
            inStock: 50,
            price: 45000,
            slug: "men_turbine_long_sleeve_tee",
            title: "Disfraz de pirata con accesorios",
            subcategoryId: 28,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740280-00-A_0_2000.jpg',
                '1740280-00-A_1.jpg',
            ],
        },
        {
            id: 5,
            description: "Vasos desechables con estampados de unicornios para fiestas infantiles.",
            inStock: 50,
            price: 40000,
            slug: "men_turbine_short_sleeve_tee",
            title: "Vasos desechables con estampados",
            subcategoryId: 20,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1741416-00-A_0_2000.jpg',
                '1741416-00-A_1.jpg',
            ],
        },
        {
            id: 6,
            description: "Platos de papel temáticos de superhéroes para fiestas de niños.",
            inStock: 0,
            price: 35000,
            slug: "men_cybertruck_owl_tee",
            title: "Platos de papel temáticos",
            subcategoryId: 17,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '7654393-00-A_2_2000.jpg',
                '7654393-00-A_3.jpg',
            ],
        },
        {
            id: 7,
            description: "Cañón de confeti con efecto multicolor ideal para grandes celebraciones.",
            inStock: 15,
            price: 35000,
            slug: "men_solar_roof_tee",
            title: "Cañón de confeti con efecto",
            subcategoryId: 7,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1703767-00-A_0_2000.jpg',
                '1703767-00-A_1.jpg',
            ],
        },
        {
            id: 8,
            description: "Cortina de lentejuelas brillante para fondos de fotos en eventos.",
            inStock: 17,
            price: 35000,
            slug: "men_let_the_sun_shine_tee",
            title: "Cortina de lentejuelas brillante",
            subcategoryId: 10,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1700280-00-A_0_2000.jpg',
                '1700280-00-A_1.jpg',
            ],
        },
        {
            id: 9,
            description: "Centro de mesa con luces LED para una decoración llamativa.",
            inStock: 12,
            price: 35000,
            slug: "men_3d_large_wordmark_tee",
            title: "Centro de mesa con luces LED",
            subcategoryId: 40,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8764734-00-A_0_2000.jpg',
                '8764734-00-A_1.jpg',
            ],
        },
        {
            id: 10,
            description: "Gorros de fiesta en colores pastel para celebraciones elegantes.",
            inStock: 5,
            price: 35000,
            slug: "men_3d_t_logo_tee",
            title: "Gorros de fiesta en colores pastel",
            subcategoryId: 36,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '7652426-00-A_0_2000.jpg',
                '7652426-00-A_1.jpg',
            ],
        },
        {
            id: 11,
            description: "Manteles temáticos de animales de la selva para fiestas infantiles.",
            inStock: 2,
            price: 35000,
            slug: "men_3d_small_wordmark_tee",
            title: "Manteles temáticos de animales ",
            subcategoryId: 41,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8528839-00-A_0_2000.jpg',
                '8528839-00-A_2.jpg',
            ],
        },
        {
            id: 12,
            description: "Banderines de tela con diseño retro para decorar cumpleaños.",
            inStock: 82,
            price: 35000,
            slug: "men_plaid_mode_tee",
            title: "Banderines de tela con diseño retro ",
            subcategoryId: 1,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1549268-00-A_0_2000.jpg',
                '1549268-00-A_2.jpg',
            ],
        },
        {
            id: 13,
            description: "Disfraz de hada con alas y varita mágica para fiestas de disfraces.",
            inStock: 24,
            price: 35000,
            slug: "men_powerwall_tee",
            title: "Disfraz de hada con alas y varita mágica",
            subcategoryId: 28,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '9877034-00-A_0_2000.jpg',
                '9877034-00-A_2.jpg',
            ],
        },
        {
            id: 14,
            description: "Velas aromáticas decorativas para ambientar eventos especiales.",
            inStock: 5,
            price: 30000,
            slug: "men_battery_day_tee",
            title: "Velas aromáticas decorativas",
            subcategoryId: 21,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1633802-00-A_0_2000.jpg',
                '1633802-00-A_2.jpg',
            ],
        },
        {
            id: 15,
            description: "Piñata en forma de estrella rellenable para celebraciones.",
            inStock: 150,
            price: 30000,
            slug: "men_cybertruck_bulletproof_tee",
            title: "Piñata en forma de estrella",
            subcategoryId: 15,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '7654399-00-A_0_2000.jpg',
                '7654399-00-A_1.jpg',
            ],
        },
        {
            id: 16,
            description: "Cajas sorpresa para souvenirs de fiestas infantiles.",
            inStock: 10,
            price: 35000,
            slug: "men_haha_yes_tee",
            title: "Cajas sorpresa para souvenirs",
            subcategoryId: 3,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '7652410-00-A_0.jpg',
                '7652410-00-A_1_2000.jpg',
            ],
        },
        {
            id: 17,
            description: "Kit de maquillaje neón para fiestas con luz negra.",
            inStock: 34,
            price: 35000,
            slug: "men_s3xy_tee",
            title: "Kit de maquillaje neón",
            subcategoryId: 63,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8764600-00-A_0_2000.jpg',
                '8764600-00-A_2.jpg',
            ],
        },
        {
            id: 18,
            description: "Palillos decorativos con figuras temáticas para aperitivos..",
            inStock: 15,
            price: 40000,
            slug: "men_3d_wordmark_long_sleeve_tee",
            title: "Palillos decorativos con figuras",
            subcategoryId: 42,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8764813-00-A_0_2000.jpg',
                '8764813-00-A_1.jpg',
            ],
        },
        {
            id: 19,
            description: "Lámparas de papel colgantes para una iluminación sofisticada.",
            inStock: 12,
            price: 40000,
            slug: "men_3d_t_logo_long_sleeve_tee",
            title: "Lámparas de papel colgantes ",
            subcategoryId: 24,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8529198-00-A_0_2000.jpg',
                '8529198-00-A_1.jpg',
            ],
        },
        {
            id: 20,
            description: "Sombreros brillantes de fiesta para despedidas de soltero/a.",
            inStock: 10,
            price: 115000,
            slug: "men_raven_lightweight_hoodie",
            title: "Sombreros brillantes ",
            subcategoryId: 36,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740245-00-A_0_2000.jpg',
                '1740245-00-A_1.jpg',
            ],
        },
        {
            id: 21,
            description: "Serpentinas de colores para lanzar en momentos especiales.",
            inStock: 10,
            price: 13000,
            slug: "chill_pullover_hoodie",
            title: "Serpentinas de colores",
            subcategoryId: 18,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740051-00-A_0_2000.jpg',
                '1740051-00-A_1.jpg',
            ],
        },
        {
            id: 22,
            description: "Invitaciones personalizadas con diseños exclusivos para eventos.",
            inStock: 100,
            price: 85000,
            slug: "men_chill_full_zip_hoodie",
            title: "Invitaciones personalizadas ",
            subcategoryId: 5,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1741111-00-A_0_2000.jpg',
                '1741111-00-A_1.jpg',
            ],
        },
        {
            id: 23,
            description: "Pañuelos temáticos para fiestas vaqueras.",
            inStock: 7,
            price: 85000,
            slug: "men_chill_quarter_zip_pullover_-_gray",
            title: "Pañuelos temáticos para fiestas vaqueras",
            subcategoryId: 43,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740140-00-A_0_2000.jpg',
                '1740140-00-A_1.jpg',
            ],
        },
        {
            id: 24,
            description: "Pulseras fluorescentes que brillan en la oscuridad.",
            inStock: 15,
            price: 85000,
            slug: "men_chill_quarter_zip_pullover_-_white",
            title: "Pulseras fluorescentes que brillan",
            subcategoryId: 63,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740145-00-A_2_2000.jpg',
                '1740145-00-A_1.jpg',
            ],
        },
        {
            id: 25,
            description: "Globos con helio de letras para formar mensajes personalizados.",
            inStock: 15,
            price: 70000,
            slug: "3d_large_wordmark_pullover_hoodie",
            title: "Globos con helio de letras para formar",
            subcategoryId: 26,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            numbers: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
            images: [
                '8529107-00-A_0_2000.jpg',
                '8529107-00-A_1.jpg',
            ],
        },
        {
            id: 26,
            description: "Máscaras de superhéroes para fiestas temáticas.",
            inStock: 13,
            price: 60000,
            slug: "cybertruck_graffiti_hoodie",
            title: "Máscaras de superhéroes",
            subcategoryId: 32,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '7654420-00-A_0_2000.jpg',
                '7654420-00-A_1_2000.jpg',
            ],
        },
        {
            id: 27,
            description: "Caminos de mesa con purpurina para decoraciones elegantes.",
            inStock: 11,
            price: 30000,
            slug: "relaxed_t_logo_hat",
            title: "Caminos de mesa con purpurina",
            subcategoryId: 44,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1657932-00-A_0_2000.jpg',
                '1657932-00-A_1.jpg',
            ],
        },
        {
            id: 28,
            description: "Bebidas en polvo con colores vibrantes para cócteles sin alcohol.",
            inStock: 13,
            price: 35000,
            slug: "thermal_cuffed_beanie",
            title: "Bebidas en polvo con colores",
            subcategoryId: 45,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740417-00-A_0_2000.jpg',
                '1740417-00-A_1.jpg',
            ],
        },
        {
            id: 29,
            description: "Cápsulas de humo de colores para efectos visuales en eventos.",
            inStock: 85,
            price: 22500,
            slug: "women_cropped_puffer_jacket",
            title: "Cápsulas de humo de colores",
            subcategoryId: 66,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740535-00-A_0_2000.jpg',
                '1740535-00-A_1.jpg',
            ],
        },
        {
            id: 30,
            description: "Tiaras con piedras brillantes para fiestas de princesas.",
            inStock: 10,
            price: 13000,
            slug: "women_chill_half_zip_cropped_hoodie",
            title: "Tiaras con piedras brillantes",
            subcategoryId: 80,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740226-00-A_0_2000.jpg',
                '1740226-00-A_1.jpg',
            ],
        },
        {
            id: 31,
            description: "Disco de luces LED portátil para animar cualquier celebración.",
            inStock: 9,
            price: 11000,
            slug: "women_raven_slouchy_crew_sweatshirt",
            title: "Disco de luces LED portátil ",
            subcategoryId: 61,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740260-00-A_0_2000.jpg',
                '1740260-00-A_1.jpg',
            ],
        },
        {
            id: 32,
            description: "Pistolas de burbujas para fiestas al aire libre",
            inStock: 10,
            price: 45000,
            slug: "women_turbine_cropped_long_sleeve_tee",
            title: "Pistolas de burbujas",
            subcategoryId: 65,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740290-00-A_0_2000.jpg',
                '1740290-00-A_1.jpg',
            ],
        },
        {
            id: 33,
            description: "Collares hawaianos de flores para eventos tropicales",
            inStock: 0,
            price: 40000,
            slug: "women_turbine_cropped_short_sleeve_tee",
            title: "Collares hawaianos de flores ",
            subcategoryId: 50,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1741441-00-A_0_2000.jpg',
                '1741441-00-A_1.jpg',
            ],
        },
        {
            id: 34,
            description: "Servilletas con estampados personalizados para fiestas exclusivas.",
            inStock: 30,
            price: 35000,
            slug: "women_t_logo_short_sleeve_scoop_neck_tee",
            title: "Servilletas con estampados personalizados",
            subcategoryId: 46,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8765090-00-A_0_2000.jpg',
                '8765090-00-A_1.jpg',
            ],
        },
        {
            id: 35,
            description: "Globos gigantes en forma de números para aniversarios y cumpleaños.",
            inStock: 16,
            price: 40000,
            slug: "women_t_logo_long_sleeve_scoop_neck_tee",
            title: "Globos gigantes en forma de números",
            subcategoryId: 26,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            numbers: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
            images: [
                '8765100-00-A_0_2000.jpg',
                '8765100-00-A_1.jpg',
            ],
        },
        {
            id: 36,
            description: "Tarjetas de agradecimiento con diseños modernos para eventos.",
            inStock: 18,
            price: 35000,
            slug: "women_small_wordmark_short_sleeve_v-neck_tee",
            title: "Tarjetas de agradecimiento con diseños ",
            subcategoryId: 5,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8765120-00-A_0_2000.jpg',
                '8765120-00-A_1.jpg',
            ],
        },
        {
            id: 37,
            description: "Carpas plegables con luces para celebraciones al aire libre.",
            inStock: 5,
            price: 35000,
            slug: "women_large_wordmark_short_sleeve_crew_neck_tee",
            title: "Carpas plegables con luces para celebraciones",
            subcategoryId: 4,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8765115-00-A_0_2000.jpg',
                '8765115-00-A_1.jpg',
            ],
        },
        {
            id: 38,
            description: "Humo de colores para efectos especiales en sesiones de fotos.",
            inStock: 16,
            price: 35000,
            slug: "women_plaid_mode_tee",
            title: "Humo de colores para efectos",
            subcategoryId: 66,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1549275-00-A_0_2000.jpg',
                '1549275-00-A_1.jpg',
            ],
        },
        {
            id: 39,
            description: "Caja de dulces temática con chocolates y caramelos variados",
            inStock: 10,
            price: 130000,
            slug: "women_powerwall_tee",
            title: "Caja de dulces temática con chocolates",
            subcategoryId: 3,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '9877040-00-A_0_2000.jpg',
                '9877040-00-A_1.jpg',
            ],
        },
        {
            id: 40,
            description: "Cinta adhesiva decorativa con brillo para envolver regalos.",
            inStock: 3,
            price: 90000,
            slug: "women_corp_jacket",
            title: "Cinta adhesiva decorativa con brillo",
            subcategoryId: 6,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '5645680-00-A_0_2000.jpg',
                '5645680-00-A_3.jpg',
            ],
        },
        {
            id: 41,
            description: "Pirotecnia fría para darle un toque especial a la fiesta.",
            inStock: 162,
            price: 100000,
            slug: "women_raven_joggers",
            title: "Pirotecnia fría",
            subcategoryId: 16,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1740270-00-A_0_2000.jpg',
                '1740270-00-A_1.jpg',
            ],
        },
        {
            id: 42,
            description: "Cajas de cartón decoradas para entregar souvenirs.",
            inStock: 10,
            price: 30000,
            slug: "kids_cybertruck_long_sleeve_tee",
            title: "Cajas de cartón decoradas",
            subcategoryId: 3,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1742694-00-A_1_2000.jpg',
                '1742694-00-A_3.jpg',
            ],
        },
        {
            id: 43,
            description: "Set de stickers para personalizar vasos y platos de fiesta.",
            inStock: 0,
            price: 25000,
            slug: "kids_scribble_t_logo_tee",
            title: "Set de stickers para personalizar ",
            subcategoryId: 20,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8529312-00-A_0_2000.jpg',
                '8529312-00-A_1.jpg',
            ],
        },
        {
            id: 44,
            description: "Gafas de colores extravagantes para animar cualquier evento.",
            inStock: 10,
            price: 25000,
            slug: "kids_cybertruck_tee",
            title: "Gafas de colores extravagantes",
            subcategoryId: 34,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8529342-00-A_0_2000.jpg',
                '8529342-00-A_1.jpg',
            ],
        },
        {
            id: 45,
            description: "Carteles personalizables con frases para photobooths.",
            inStock: 10,
            price: 30000,
            slug: "kids_racing_stripe_tee",
            title: "Carteles personalizables ",
            subcategoryId: 66,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8529354-00-A_0_2000.jpg',
                '8529354-00-A_1.jpg',
            ],
        },
        {
            id: 46,
            description: "Chapas con frases divertidas para despedidas de soltero/a.",
            inStock: 10,
            price: 30000,
            slug: "kids_3d_t_logo_tee",
            title: "Chapas con frases divertidas",
            subcategoryId: 81,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '7652465-00-A_0_2000.jpg',
                '7652465-00-A_1.jpg',
            ],
        },
        {
            id: 47,
            description: "Guantes LED que cambian de color al ritmo de la música.",
            inStock: 10,
            price: 30000,
            slug: "kids_checkered_tee",
            title: "Guantes LED que cambian de color",
            subcategoryId: 63,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '100042307_0_2000.jpg',
                '100042307_alt_2000.jpg',
            ],
        },
        {
            id: 48,
            description: "Botellas de champán decorativas con efectos brillantes",
            inStock: 16,
            price: 25000,
            slug: "made_on_earth_by_humans_onesie",
            title: "Botellas de champán decorativas",
            subcategoryId: 45,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1473809-00-A_1_2000.jpg',
                '1473809-00-A_alt.jpg',
            ],
        },
        {
            id: 49,
            description: "Camisas hawaianas para fiestas temáticas tropicales.",
            inStock: 0,
            price: 30000,
            slug: "scribble_t_logo_onesie",
            title: "Camisas hawaianas",
            subcategoryId: 50,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '8529387-00-A_0_2000.jpg',
                '8529387-00-A_1.jpg',
            ],
        },
        {
            id: 50,
            description: "Moldes de hielo con formas divertidas para bebidas especiales.",
            inStock: 10,
            price: 30000,
            slug: "zero_emissions_(almost)_onesie",
            title: "Moldes de hielo con formas divertidas",
            subcategoryId: 45,
            sizes: ['S', 'M', 'L'],
            colors: ['#ff0000', '#00ff00', '#0000ff'],
            images: [
                '1473834-00-A_2_2000.jpg',
                '1473829-00-A_2_2000.jpg',
            ],
        },
    ]
}