interface SeedSubcategories {
    id: number,
    name: string,
    categoryId: number,
}

export const subcategories: SeedSubcategories[] = [
    { id: 1, name: "Banderines", categoryId: 1 },
    { id: 2, name: "Bases para pastel", categoryId: 1 },
    { id: 3, name: "Cajas", categoryId: 1 },
    { id: 4, name: "Carpas", categoryId: 1 },
    { id: 5, name: "Cartas", categoryId: 1 },
    { id: 6, name: "Cintas", categoryId: 1 },
    { id: 7, name: "Confeti", categoryId: 1 },
    { id: 8, name: "Copas", categoryId: 1 },
    { id: 9, name: "Cortadores", categoryId: 1 },
    { id: 10, name: "Cortinas", categoryId: 1 },
    { id: 11, name: "Cubiertos", categoryId: 1 },
    { id: 12, name: "Guirnaldas", categoryId: 1 },
    { id: 13, name: "Lamparas", categoryId: 1 },
    { id: 14, name: "Medidores", categoryId: 1 },
    { id: 15, name: "Piñatas", categoryId: 1 },
    { id: 16, name: "Pirotecnia", categoryId: 1 },
    { id: 17, name: "Platos", categoryId: 1 },
    { id: 18, name: "Serpentinas", categoryId: 1 },
    { id: 19, name: "Servilletas", categoryId: 1 },
    { id: 20, name: "Vasos", categoryId: 1 },
    { id: 21, name: "Velas", categoryId: 1 },

    { id: 22, name: "Base para globos", categoryId: 2 },
    { id: 23, name: "Burbujas", categoryId: 2 },
    { id: 24, name: "Cantoyas", categoryId: 2 },
    { id: 25, name: "Infladores", categoryId: 2 },
    { id: 26, name: "Metalizados", categoryId: 2 },
    { id: 27, name: "Personaje", categoryId: 2 },

    { id: 28, name: "Disfraces completos", categoryId: 3 },
    { id: 29, name: "Pelucas", categoryId: 3 },
    { id: 30, name: "Diademas", categoryId: 3 },
    { id: 31, name: "Bigotes", categoryId: 3 },
    { id: 32, name: "Mascaras", categoryId: 3 },
    { id: 33, name: "Corbatas", categoryId: 3 },
    { id: 34, name: "Gafas", categoryId: 3 },
    { id: 35, name: "Collares", categoryId: 3 },
    { id: 36, name: "Gorros y sombreros", categoryId: 3 },
    { id: 37, name: "Pompones", categoryId: 3 },
    { id: 38, name: "Medias", categoryId: 3 },
    { id: 39, name: "Pañoletas", categoryId: 3 },

    { id: 40, name: "Centro de Mesa", categoryId: 5 },
    { id: 41, name: "Manteles", categoryId: 5 },
    { id: 42, name: "Palillos decorativos", categoryId: 5 },
    { id: 43, name: "Pañuelos", categoryId: 5 },
    { id: 44, name: "Caminos", categoryId: 5 },
    { id: 45, name: "Bebidas", categoryId: 5 },
    { id: 46, name: "Servilletas", categoryId: 5 },

    { id: 47, name: "Fiesta Mexicana", categoryId: 6 },
    { id: 48, name: "Rock", categoryId: 6 },
    { id: 49, name: "HoraLoca", categoryId: 6 },
    { id: 50, name: "Hawaiana", categoryId: 6 },
    { id: 51, name: "Colombiana", categoryId: 6 },
    { id: 52, name: "Aguacates", categoryId: 6 },
    { id: 53, name: "Casino", categoryId: 6 },
    { id: 54, name: "Emoji", categoryId: 6 },
    { id: 55, name: "Hollywood", categoryId: 6 },
    { id: 56, name: "Pride", categoryId: 6 },
    { id: 57, name: "50 años", categoryId: 6 },
    { id: 58, name: "Star Wars", categoryId: 6 },
    { id: 59, name: "Harry Potter", categoryId: 6 },
    { id: 60, name: "Vaqueros", categoryId: 6 },
    { id: 61, name: "Disco", categoryId: 6 },
    { id: 62, name: "Margaritas", categoryId: 6 },
    { id: 63, name: "Fiesta de Neon", categoryId: 6 },

    { id: 64, name: "Niñas", categoryId: 7 },
    { id: 65, name: "Niños", categoryId: 7 },

    { id: 66, name: "Revelación de Genero", categoryId: 8 },
    { id: 67, name: "Baby Shower", categoryId: 8 },
    { id: 68, name: "Grados", categoryId: 8 },
    { id: 69, name: "Bautizo", categoryId: 8 },
    { id: 70, name: "Primera Comunión", categoryId: 8 },
    { id: 71, name: "Aniversario", categoryId: 8 },
    { id: 72, name: "Bienvenida", categoryId: 8 },
    { id: 73, name: "Navidad", categoryId: 8 },
    { id: 74, name: "Despedida", categoryId: 8 },
    { id: 75, name: "Halloween", categoryId: 8 },
    { id: 76, name: "San Valentín", categoryId: 8 },

    { id: 77, name: "Velos", categoryId: 9 },
    { id: 78, name: "Sets", categoryId: 9 },
    { id: 79, name: "Bandas", categoryId: 9 },
    { id: 80, name: "Tiaras", categoryId: 9 },
    { id: 81, name: "Chapas", categoryId: 9 },
]